In [58]:
import pandas as pd

In [59]:
dim_video = pd.read_csv("warehouse/dim_video.csv")
dim_video = pd.DataFrame(dim_video)
display(dim_video)

,video_id,title,channel_id,thumbnail,duration,tags,category_id,keyword_id,topic_id,publish_time
0,JJXKkfUYM9c,Honor X9d Review - Masakit man pero Kailangan !,UC7iCSSpCsNw34E1o0DwgJBA,https://i.ytimg.com/vi/JJXKkfUYM9c/default.jpg,PT20M30S,NaN,28.0,61.0,7.0,2026-01-23T10:21:18Z
1,JXZCpQsY0e4,"ReviewTechUSA Is Back (I Made A Mistake, Here&...",UCOuKecIw7ObKsLCMimUbbMA,https://i.ytimg.com/vi/JXZCpQsY0e4/default.jpg,PT6M29S,"richard masucci,rich masucci,reviewtechusa mel...",22.0,61.0,7.0,2025-12-18T21:50:27Z
2,mkcgVN90zl0,This Gadget BRICKS Your Phone!,UCMiJRAwDNSNzuYeN2uWa0pA,https://i.ytimg.com/vi/mkcgVN90zl0/default.jpg,PT48S,NaN,28.0,61.0,7.0,2025-02-21T14:57:07Z
3,ObqHKHoSE5Y,Samsung S26 Ultra Hands on - What&#39;s ACTUAL...,UCMiJRAwDNSNzuYeN2uWa0pA,https://i.ytimg.com/vi/ObqHKHoSE5Y/default.jpg,PT14M17S,"samsung,galaxy,s26,s26 ultra,s26 ultra review,...",28.0,61.0,7.0,2026-02-25T18:00:00Z
4,RvP-uVNwnXo,Dope Tech: STILL so good!,UCBJycsmduvYEL83R_U4JriQ,https://i.ytimg.com/vi/RvP-uVNwnXo/default.jpg,PT16M54S,"Dope Tech,dope tech,MKBHD,MX Master 4,Devialet...",28.0,61.0,7.0,2025-11-21T19:00:50Z
...,...,...,...,...,...,...,...,...,...,...
21081,tjdAvErwwEE,Lisandro Cuxi x Loony Johnson - SIKI SIKI (Remix),UCWFtq-yPoyeuFP3eaDcQHUQ,https://i.ytimg.com/vi/tjdAvErwwEE/default.jpg,PT3M8S,NaN,10.0,97.0,10.0,2026-04-15T16:00:39Z
21082,PA2aWF37Ljk,TEDDY AFRO - ጀምበር - Jember | Track 18 (Offici...,UCydlocDyvRtFmMffKytKqgQ,https://i.ytimg.com/vi/PA2aWF37Ljk/default.jpg,PT6M34S,NaN,10.0,97.0,10.0,2026-04-16T11:00:24Z
21083,2bHMD_fUVpo,Calema - Chuva De Amor,UC4Sx0tMqY7Z6VZKL8Z76tog,https://i.ytimg.com/vi/2bHMD_fUVpo/default.jpg,PT3M51S,"calema,amar pela metade,calema amar pela metad...",10.0,97.0,10.0,2026-04-04T11:00:06Z
21084,wHPX1XWexLg,J'ai RELANCÉ Brawl Stars après 1 an..,UCiFyJ_EBmF2XJuR9buWE_3A,https://i.ytimg.com/vi/wHPX1XWexLg/default.jpg,PT21M29S,"unchained,unchained_off,unchained fortnite,for...",20.0,57.0,6.0,2026-04-27T15:04:01Z
21085,oFxjmRTggv0,Crimson Desert - LE PLUS MAUVAIS OPEN WORLD (d...,UC4peNo-31r7fhQZgu0_JRIA,https://i.ytimg.com/vi/oFxjmRTggv0/default.jpg,PT34M1S,NaN,20.0,57.0,6.0,2026-04-10T15:00:34Z

In [60]:
dim_video.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21086 entries, 0 to 21085
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   video_id      21086 non-null  object
 1   title         21086 non-null  object
 2   channel_id    21086 non-null  object
 3   thumbnail     21086 non-null  object
 4   duration      20743 non-null  object
 5   tags          13180 non-null  object
 6   category_id   20743 non-null  float64
 7   keyword_id    21086 non-null  float64
 8   topic_id      21086 non-null  float64
 9   publish_time  21086 non-null  object
dtypes: float64(3), object(7)
memory usage: 1.6+ MB

In [61]:
dim_video.isnull().sum()

video_id           0
title              0
channel_id         0
thumbnail          0
duration         343
tags            7906
category_id      343
keyword_id         0
topic_id           0
publish_time       0
dtype: int64

có nhiều video không để tags nên ta sẽ không xử lý nó

In [62]:
dim_video = dim_video.dropna(subset=["duration"])

In [63]:
import isodate

def parse_duration(x):
    try:
        return int(isodate.parse_duration(x).total_seconds())
    except:
        return None

dim_video["duration"] = dim_video["duration"].apply(parse_duration)

chuyển Duration thành giây

In [64]:
dim_video["category_id"] = dim_video["category_id"].astype(int)
dim_video["keyword_id"] = dim_video["keyword_id"].astype(int)
dim_video["topic_id"] = dim_video["topic_id"].astype(int)

ép kiểu từ numeric thành int

In [65]:
dim_channel = pd.read_csv("warehouse/dim_channel.csv")
dim_channel = pd.DataFrame(dim_channel)
display(dim_channel)

,channel_id,channel_title,country,subscriber_count,video_count,total_views
0,UC6AhuKHE0b2SdAnPUFpmFJQ,Friend,GB,1610000,963,633924238
1,UCW3Ms3ZxVaZUniP-HifWCDg,Karry Kraft,IN,1130000,280,399704538
2,UC-E2AW4oA0wA4RhnVWaU1hg,Quangg Replay,VN,96900,337,20984470
3,UCFlp6RS46B4KHuyjuEJVMIQ,Sandal Goib,ID,1670000,1440,1771791617
4,UClv_LVQmiiXQV7U7hneGL-w,D.R.K limitless,IN,872000,296,125511109
...,...,...,...,...,...,...
17724,UCRNj_5QPDKO8W8AS3VjZ6yg,AKMAL',RU,323000,235,380790126
17725,UCofK-jm2oG6GqkYp7Vw3U6g,Richie Mexa,MX,6470,82,27705014
17726,UCD2w1rGcJc99akNKluz_FDw,412 - El Programa Del Fútbol,Unknown,671000,322,137923113
17727,UCj9rK3jt8qmih4mZX0UL67g,DeGoBooM,CL,23800000,5859,7815376281
17728,UC4peNo-31r7fhQZgu0_JRIA,Sheshounet,FR,1240000,273,268917608

In [66]:
dim_topic = pd.read_csv("warehouse/dim_topic.csv")
dim_topic = pd.DataFrame(dim_topic)
display(dim_topic)

   topic_id     topic_name
0         1  entertainment
1         2      challenge
2         3           vlog
3         4         travel
4         5           food
5         6         gaming
6         7     technology
7         8      education
8         9        fitness
9        10          music

In [67]:
dim_time = pd.read_csv("warehouse/dim_time.csv")
dim_time = pd.DataFrame(dim_time)
display(dim_time)

          time_id  year  month  day  hour  weekday
0      2025062818  2025      6   28    18        5
1      2025101003  2025     10   10     3        4
2      2025071206  2025      7   12     6        5
3      2026022818  2026      2   28    18        5
4      2025060717  2025      6    7    17        5
...           ...   ...    ...  ...   ...      ...
11312  2026042106  2026      4   21     6        1
11313  2026041905  2026      4   19     5        6
11314  2026040813  2026      4    8    13        2
11315  2026050920  2026      5    9    20        5
11316  2026050921  2026      5    9    21        5

[11317 rows x 6 columns]

In [68]:
dim_keyword = pd.read_csv("warehouse/dim_keyword.csv")
dim_keyword = pd.DataFrame(dim_keyword)
display(dim_keyword)

    keyword_id                     keyword  topic_id
0            1    funny videos compilation         1
1            2       funniest moments ever         1
2            3    viral videos compilation         1
3            4            best funny clips         1
4            5  instant regret compilation         1
..         ...                         ...       ...
95          96                 chill music        10
96          97        official music video        10
97          98      live music performance        10
98          99              top music hits        10
99         100            kpop music video        10

[100 rows x 3 columns]

In [69]:
fact_video_metrics = pd.read_csv("warehouse/fact_video_metrics.csv")
fact_video_metrics = pd.DataFrame(fact_video_metrics)
display(fact_video_metrics)

,video_id,time_id,views,likes,comment_count,crawl_timestamp,is_trending
0,JJXKkfUYM9c,2026031012,95250,2781,2272,2026-03-10 12:40:34.402602,NaN
1,JXZCpQsY0e4,2026031012,54979,4922,1660,2026-03-10 12:40:34.402602,NaN
2,mkcgVN90zl0,2026031012,11565022,556461,5344,2026-03-10 12:40:34.402602,NaN
3,ObqHKHoSE5Y,2026031012,4042883,123695,9221,2026-03-10 12:40:34.402602,NaN
4,RvP-uVNwnXo,2026031012,3844230,90816,2448,2026-03-10 12:40:34.402602,NaN
...,...,...,...,...,...,...,...
74978,tjdAvErwwEE,2026050914,611392,9604,423,2026-05-09 14:36:18.765630,True
74979,PA2aWF37Ljk,2026050914,9506434,218714,30856,2026-05-09 14:36:18.765630,True
74980,2bHMD_fUVpo,2026050914,1625330,23457,848,2026-05-09 14:36:18.765630,True
74981,wHPX1XWexLg,2026050914,1161988,68414,7878,2026-05-09 14:36:18.765630,True
74982,oFxjmRTggv0,2026050914,1116332,78114,3217,2026-05-09 14:36:18.765630,True

In [70]:
fact_comments = pd.read_csv("warehouse/fact_comments.csv")
fact_comments = pd.DataFrame(fact_comments)
display(fact_comments)

,comment_id,video_id,time_id,comment_text,like_count
0,UgxIPKOQXWACvLf4fYF4AaABAg,JJXKkfUYM9c,2026012413,Sana ako mabunot need ko tlga cp kasi nag haha...,10
1,UgwOuKkXxF_M4l_PvZB4AaABAg,JJXKkfUYM9c,2026031004,Yan nlang bilhin ko❤🥰,0
2,UgzqCZ7H73rJ0rAAOAt4AaABAg,JJXKkfUYM9c,2026030909,Pang regalo lng lods sa anak ko salamat❤❤❤,0
3,UgysoXXsEaAiveRJ57R4AaABAg,JJXKkfUYM9c,2026030806,😂😂😂watching gamit honor x9d matibay nga po yan,0
4,UgxqqhHLeLNn_bYMqBJ4AaABAg,JJXKkfUYM9c,2026030800,Honox9d din unit ko pero dko susubukan yan😅😅😅😅,0
...,...,...,...,...,...
1361041,UgwYgk3ZjNo2DzlmCzR4AaABAg,oFxjmRTggv0,2026042322,"Merci, je n’osez pas franchir le pas sur ce je...",0
1361042,UgyA9js-xW7dicQNvIR4AaABAg,oFxjmRTggv0,2026042320,"Petit commentaire pour le soutiens, merci pour...",0
1361043,Ugx6bv4WkwxRfQQ1NDd4AaABAg,oFxjmRTggv0,2026042319,Merci pour cette vidéo ! Excellent ! Je n'ai q...,0
1361044,Ugw5UM9v4oX4UD4EQJV4AaABAg,oFxjmRTggv0,2026042318,Il a coulé avec le code,0
1361045,UgzfndCRElQTVSKFUd14AaABAg,oFxjmRTggv0,2026042316,Ce succès de malade!,0

In [71]:
fact_comments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1361046 entries, 0 to 1361045
Data columns (total 5 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   comment_id    1361046 non-null  object
 1   video_id      1361046 non-null  object
 2   time_id       1361046 non-null  int64
 3   comment_text  1361046 non-null  object
 4   like_count    1361046 non-null  int64
dtypes: int64(2), object(3)
memory usage: 51.9+ MB

In [72]:
fact_comments.isnull().sum()

comment_id      0
video_id        0
time_id         0
comment_text    0
like_count      0
dtype: int64

In [73]:
fact_comments = fact_comments.dropna(subset=["comment_text"])

In [74]:
fact_comments

,comment_id,video_id,time_id,comment_text,like_count
0,UgxIPKOQXWACvLf4fYF4AaABAg,JJXKkfUYM9c,2026012413,Sana ako mabunot need ko tlga cp kasi nag haha...,10
1,UgwOuKkXxF_M4l_PvZB4AaABAg,JJXKkfUYM9c,2026031004,Yan nlang bilhin ko❤🥰,0
2,UgzqCZ7H73rJ0rAAOAt4AaABAg,JJXKkfUYM9c,2026030909,Pang regalo lng lods sa anak ko salamat❤❤❤,0
3,UgysoXXsEaAiveRJ57R4AaABAg,JJXKkfUYM9c,2026030806,😂😂😂watching gamit honor x9d matibay nga po yan,0
4,UgxqqhHLeLNn_bYMqBJ4AaABAg,JJXKkfUYM9c,2026030800,Honox9d din unit ko pero dko susubukan yan😅😅😅😅,0
...,...,...,...,...,...
1361041,UgwYgk3ZjNo2DzlmCzR4AaABAg,oFxjmRTggv0,2026042322,"Merci, je n’osez pas franchir le pas sur ce je...",0
1361042,UgyA9js-xW7dicQNvIR4AaABAg,oFxjmRTggv0,2026042320,"Petit commentaire pour le soutiens, merci pour...",0
1361043,Ugx6bv4WkwxRfQQ1NDd4AaABAg,oFxjmRTggv0,2026042319,Merci pour cette vidéo ! Excellent ! Je n'ai q...,0
1361044,Ugw5UM9v4oX4UD4EQJV4AaABAg,oFxjmRTggv0,2026042318,Il a coulé avec le code,0
1361045,UgzfndCRElQTVSKFUd14AaABAg,oFxjmRTggv0,2026042316,Ce succès de malade!,0

vì ta sẽ sử dụng comment để làm Sentiment model nên sẽ tiến hành xóa bỏ Null đi

In [75]:
dim_video.to_csv("warehouse/dim_video.csv", index=False)
dim_channel.to_csv("warehouse/dim_channel.csv", index=False)
dim_topic.to_csv("warehouse/dim_topic.csv", index=False)
dim_time.to_csv("warehouse/dim_time.csv", index=False)
dim_keyword.to_csv("warehouse/dim_keyword.csv", index=False)
fact_video_metrics.to_csv("warehouse/fact_video_metrics.csv", index=False)
fact_comments.to_csv("warehouse/fact_comments.csv", index=False)

print("Đã lưu tất cả các bảng")

Đã lưu tất cả các bảng

In [76]:
fact_comments

,comment_id,video_id,time_id,comment_text,like_count
0,UgxIPKOQXWACvLf4fYF4AaABAg,JJXKkfUYM9c,2026012413,Sana ako mabunot need ko tlga cp kasi nag haha...,10
1,UgwOuKkXxF_M4l_PvZB4AaABAg,JJXKkfUYM9c,2026031004,Yan nlang bilhin ko❤🥰,0
2,UgzqCZ7H73rJ0rAAOAt4AaABAg,JJXKkfUYM9c,2026030909,Pang regalo lng lods sa anak ko salamat❤❤❤,0
3,UgysoXXsEaAiveRJ57R4AaABAg,JJXKkfUYM9c,2026030806,😂😂😂watching gamit honor x9d matibay nga po yan,0
4,UgxqqhHLeLNn_bYMqBJ4AaABAg,JJXKkfUYM9c,2026030800,Honox9d din unit ko pero dko susubukan yan😅😅😅😅,0
...,...,...,...,...,...
1361041,UgwYgk3ZjNo2DzlmCzR4AaABAg,oFxjmRTggv0,2026042322,"Merci, je n’osez pas franchir le pas sur ce je...",0
1361042,UgyA9js-xW7dicQNvIR4AaABAg,oFxjmRTggv0,2026042320,"Petit commentaire pour le soutiens, merci pour...",0
1361043,Ugx6bv4WkwxRfQQ1NDd4AaABAg,oFxjmRTggv0,2026042319,Merci pour cette vidéo ! Excellent ! Je n'ai q...,0
1361044,Ugw5UM9v4oX4UD4EQJV4AaABAg,oFxjmRTggv0,2026042318,Il a coulé avec le code,0
1361045,UgzfndCRElQTVSKFUd14AaABAg,oFxjmRTggv0,2026042316,Ce succès de malade!,0

# Data Cleaning

### Dim Tables